#This file contains 3 manifests
# * ServiceAccount
# * Role
# * RoleBinding
#
# TIP: use kubectl command to generate manifests
# kubectl create sa app-deployer -n production --dry-run=client -o yaml
# kubectl create role app-deployer -n production --resource=pods,deployments --verb=create,list,delete --dry-run=client -o yaml
# kubectl create rolebinding app-deployer  -n production --role=app-deployer --serviceaccount=production:app-deployer --dry-run=client -o yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-deployer
  namespace: production
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: app-deployer
  namespace: production
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - list
  - delete
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - list
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: app-deployer
  namespace: production
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: app-deployer
subjects:
- kind: ServiceAccount
  name: app-deployer
  namespace: production